In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
b = np.array([1,0,0])
a<b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [134]:
temp = np.array([4,1,0,-2,5,7,-3,0,0,5,0,-1,3,6,9,5,7,11,9,6,0])
newarr = np.array_split(temp,2)
newarr

[array([ 4,  1,  0, -2,  5,  7, -3,  0,  0,  5,  0]),
 array([-1,  3,  6,  9,  5,  7, 11,  9,  6,  0])]

In [125]:
#2
temp.mean()

2.032258064516129

In [67]:
#3
print(temp.max())

11


In [68]:
#4
print(temp.argmax())

17


In [69]:
#5
max_temp_day = temp.argmax()
temp[max_temp_day] = 0
temp

array([ 4,  1,  0, -2,  5,  7, -3,  0,  0,  5,  0, -1,  3,  6,  9,  5,  7,
        0,  9,  6,  0])

In [71]:
#6
len(temp[temp < 0])

3

In [72]:
#7

print(np.any(temp>10))

print(np.any(temp>5))

False
True


In [73]:
#8
print(np.all(temp < 10))

True


In [74]:
#9
temp_diff = np.abs(np.diff(temp))
print(temp_diff)
print(temp_diff> 5)
print(np.sum(temp_diff >5))

[ 3  1  2  7  2 10  3  0  5  5  1  4  3  3  4  2  7  9  3  6]
[False False False  True False  True False False False False False False
 False False False False  True  True False  True]
5


In [79]:
#10
temp = temp +1
temp

array([ 5,  2,  1, -1,  6,  8, -2,  1,  1,  6,  1,  0,  4,  7, 10,  6,  8,
        1, 10,  7,  1])

In [80]:
#11
len(temp)

21

In [83]:
#12
arr = np.random.randint(-5,5,(31-len(temp)))
arr

array([ 2, -4, -4, -4, -5, -5, -1,  3,  1, -2])

In [128]:
#13
#temp = np.concatenate((temp,arr))
temp = np.append(temp,arr)
temp

array([ 5,  2,  1, -1,  6,  8, -2,  1,  1,  6,  1,  0,  4,  7, 10,  6,  8,
        1, 10,  7,  1,  2, -4, -4, -4, -5, -5, -1,  3,  1, -2,  2, -4, -4,
       -4, -5, -5, -1,  3,  1, -2,  2, -4, -4, -4, -5, -5, -1,  3,  1, -2])

In [85]:
temp

array([ 5,  2,  1, -1,  6,  8, -2,  1,  1,  6,  1,  0,  4,  7, 10,  6,  8,
        1, 10,  7,  1,  2, -4, -4, -4, -5, -5, -1,  3,  1, -2])

In [86]:
a= np.array([-5,3])
b = np.array([2,4])


In [129]:
#1
c = a+b
c
#Answer is Б

array([6, 2, 5])

In [89]:
#2
a= np.array([3,-6])
b = np.array([1,-2])
c = b - a
print(c)
#Answer is Б

[-2  4]


In [121]:
#3
a= np.array([-3,2])
b = np.array([1,-4])
print(np.dot(a,b))
#Answer is B

-11


In [99]:
#4
a= np.array([4,-3])
b = np.array([0,-6])
res = np.sqrt(np.sum(np.abs(a-b)**2))
print(res)
#Answer is A

5.0


In [103]:
#5
a= np.array([-4,8])
b = np.array([3,7])
c= 2*a -b
print(c)
#Answer is A

[-11   9]


In [109]:
#6
a= np.array([0,2,-2])
b = np.array([1,0,-1])

In [110]:
sc = np.sum(a*b)
mod1 = np.sqrt(np.sum(a**2))
mod2 = np.sqrt(np.sum(b**2))
mod2

1.4142135623730951

In [111]:
res = sc/(mod1*mod2)

In [112]:
res

0.4999999999999999

In [123]:
#7
a= np.array([3,-3,3])
b = np.array([3,5,2])

In [124]:
res = np.dot(a,b)
answ =  "Перпендикулярні" if res == 0 else "Неперпендикулярні"
print(answ)

Перпендикулярні


In [119]:

#8
a= np.array([3,-1,2])
b = np.array([6,2,-4])
cross = np.cross(a,b)
if np.all(cross == 0):
    print("Collinear")
else:
    print("Not Collinear")

Not Collinear
