In [190]:
import numpy as np

In [191]:
#1
arr = np.array([739, 642, 125, 984, 490, 712, 635,
643, 189, 370, 752, 397, 384, 756, 171, 153, 155, 695, 831, 618, 898, 115, 624, 592, 684, 799,
461, 96])
arr

array([739, 642, 125, 984, 490, 712, 635, 643, 189, 370, 752, 397, 384,
       756, 171, 153, 155, 695, 831, 618, 898, 115, 624, 592, 684, 799,
       461,  96])

In [192]:
#2
new_arr = arr.reshape(-1,7)
new_arr

array([[739, 642, 125, 984, 490, 712, 635],
       [643, 189, 370, 752, 397, 384, 756],
       [171, 153, 155, 695, 831, 618, 898],
       [115, 624, 592, 684, 799, 461,  96]])

In [193]:
#3
new_arr.sum(axis =0)

array([1668, 1608, 1242, 3115, 2517, 2175, 2385])

In [194]:
#4
new_arr.mean(axis =1)

array([618.14285714, 498.71428571, 503.        , 481.57142857])

In [195]:
#5
print(new_arr.sum(axis=0))
print(new_arr.sum(axis=0).argmax())

[1668 1608 1242 3115 2517 2175 2385]
3


In [196]:
#6
days_sum = new_arr.sum(axis=0)
np.where(days_sum > 2500)

(array([3, 4], dtype=int64),)

In [197]:
#7
weekday_sales = days_sum[:-2].sum()
weekdend_sales = days_sum[-2:].sum()
weekdend_sales > weekday_sales

False

In [198]:
#8
new_arr[:,-2:] = 0
new_arr

array([[739, 642, 125, 984, 490,   0,   0],
       [643, 189, 370, 752, 397,   0,   0],
       [171, 153, 155, 695, 831,   0,   0],
       [115, 624, 592, 684, 799,   0,   0]])

In [199]:
#9
new_arr = np.delete(new_arr,0,1)
new_arr

array([[642, 125, 984, 490,   0,   0],
       [189, 370, 752, 397,   0,   0],
       [153, 155, 695, 831,   0,   0],
       [624, 592, 684, 799,   0,   0]])

In [200]:
#10
new_monday_data = np.array([205, 190, np.NaN, 117]).reshape(-1,1)
new_monday_data

array([[205.],
       [190.],
       [ nan],
       [117.]])

In [201]:
arr_with_new_monday = np.hstack([new_monday_data,new_arr])
arr_with_new_monday

array([[205., 642., 125., 984., 490.,   0.,   0.],
       [190., 189., 370., 752., 397.,   0.,   0.],
       [ nan, 153., 155., 695., 831.,   0.,   0.],
       [117., 624., 592., 684., 799.,   0.,   0.]])

In [202]:
#11
new_month_sales = np.nansum(arr_with_new_monday)
new_month_sales

8994.0

In [203]:
#12
transposed = arr_with_new_monday.T
transposed

array([[205., 190.,  nan, 117.],
       [642., 189., 153., 624.],
       [125., 370., 155., 592.],
       [984., 752., 695., 684.],
       [490., 397., 831., 799.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.]])

In [204]:
##PART 2

In [205]:
#1
a = np.array([1,2,3,-2,1,-1,-2,-3,3,2,-1,2,2,-3,2,1]).reshape(4,4)
b = np.array([1,-4,-6,-4])
x_first = np.linalg.solve(a, b)
x_first

array([-2.0625    ,  0.44791667,  0.72916667,  0.01041667])

In [206]:
np.allclose(np.dot(a, x), b)

True

In [207]:
#2
x_second = np.dot(np.linalg.inv(a),b)
x_second

array([-2.0625    ,  0.44791667,  0.72916667,  0.01041667])

In [208]:
np.allclose(np.dot(a, x), b)

True

In [209]:
a

array([[ 1,  2,  3, -2],
       [ 1, -1, -2, -3],
       [ 3,  2, -1,  2],
       [ 2, -3,  2,  1]])

In [210]:
#3

In [211]:
det_A = np.linalg.det(a)


A1 = a.copy()
A1[:, 0] = b
det_A1 = np.linalg.det(A1)

A2 = a.copy()
A2[:, 1] = b
det_A2 = np.linalg.det(A2)

A3 = a.copy()
A3[:, 2] = b
det_A3 = np.linalg.det(A3)

A4 = a.copy()
A4[:, 3] = b
det_A4 = np.linalg.det(A4)

x1 = det_A1 / det_A
x2 = det_A2 / det_A
x3 = det_A3 / det_A
x4 = det_A4 / det_A
x_cramers = np.array([x1,x2,x3,x4])
x_cramers

array([-2.0625    ,  0.44791667,  0.72916667,  0.01041667])

In [212]:
print(x_first)
print(x_second)
print(x_cramers)

[-2.0625      0.44791667  0.72916667  0.01041667]
[-2.0625      0.44791667  0.72916667  0.01041667]
[-2.0625      0.44791667  0.72916667  0.01041667]


In [213]:
np.allclose(x_first,x_second) and np.allclose(x_first,x_cramers)

True

In [214]:
#Part 3


In [215]:
A_arr = np.array([4,5,-2,3,-1,0,4,2,7]).reshape(3,3)
B_arr = np.array([2,1,-1,0,1,3,5,7,3]).reshape(3,3)
res = 3*A_arr - (A_arr - 2*B_arr)*B_arr
res

array([[12, 12, -6],
       [ 9,  0, 18],
       [42, 90, 18]])

In [216]:
m=np.array([[1,2],[3,4], [5,6]])
h=np.array([1,0])
m*h

array([[1, 0],
       [3, 0],
       [5, 0]])